[package]
name = "moproxy"
version = "0.2.5"
authors = ["sorz <me@sorz.org>"]
edition = "2018"

[dependencies]
libc = "0.2"
nix = "0.14"
rand = "0.7"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-uds = "0.2"
tokio-signal = "0.2"
net2 = "0.2"
clap = {version = "2.33", features = ["yaml"]}
log = "0.4"
env_logger = "0.6"
serde = {version = "1.0", features = ["rc"]}
serde_json = "1.0"
serde_derive = "1.0"
rust-ini = "0.13"
hyper = {version = "0.12", default-features = false, optional = true}
parking_lot = {version = "0.8", features = ["serde"]}

[features]
default = ["web_console"]
web_console = ["hyper"]

