[package]
name = "moproxy"
version = "0.2.6"
authors = ["sorz <me@sorz.org>"]
edition = "2018"

[dependencies]
libc = "0.2"
nix = "0.14"
rand = "0.7"
futures = "0.1"
tokio = "0.2"
tokio-signal = "0.3"
net2 = "0.2"
clap = {version = "2.33", features = ["yaml"]}
log = "0.4"
env_logger = "0.6"
serde = {version = "1.0", features = ["rc"]}
serde_json = "1.0"
serde_derive = "1.0"
rust-ini = "0.13"
hyper = {version = "0.13.0-a.0", optional = true, default-features = false}
parking_lot = {version = "0.8", features = ["serde"]}
http = "0.1"
prettytable-rs = "0.8"
regex = "1"
lazy_static = "1.3"
number_prefix = "0.3"
futures03 = { package = "futures-preview", version = "0.3.0-alpha.17", default-features = false, features = ["compat"] }
httparse = "1.3"

[patch.crates-io]
tokio = { git = 'https://github.com/tokio-rs/tokio', features = ['async-traits'] }
tokio-signal = { git = 'https://github.com/tokio-rs/tokio' }

hyper = { git = 'https://github.com/hyperium/hyper' }


[features]
default = ["web_console"]
web_console = ["hyper"]
