[package]
name = "moproxy"
version = "0.1.0"
authors = ["sorz <me@sorz.org>"]

[dependencies]
libc = "0.2"
nix = "0.9"
rand = "0.3"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-timer = "0.1"
net2 = "0.2"
clap = {version = "2.27", features = ["yaml"]}
log = "0.3"
env_logger = "0.4"
rustful = {version = "0.9", default-features = false}

