[package]
name = "moproxy"
version = "0.1.0"
authors = ["sorz <me@sorz.org>"]

[dependencies]
libc = "0.2.24"
nix = "0.8.1"
rand = "0.3"
futures = "0.1.14"
tokio-core = "0.1.8"
tokio-io = "0.1.2"
net2 = "0.2"
clap = {version = "2.25", features = ["yaml"]}
log = "0.3"
simplelog = "0.4"
