[package]
name = "moproxy"
version = "0.2.3"
authors = ["sorz <me@sorz.org>"]

[dependencies]
libc = "0.2"
nix = "0.11"
rand = "0.5"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-uds = "0.1"
net2 = "0.2"
clap = {version = "2.32", features = ["yaml"]}
log = "0.4"
env_logger = "0.5"
serde = {version = "1.0", features = ["rc"]}
serde_json = "1.0"
serde_derive = "1.0"
rust-ini = "0.13"
hyper = {version = "0.12", default-features = false}
