[package]
name = "moproxy"
version = "0.2.6"
authors = ["sorz <me@sorz.org>"]
edition = "2018"

[dependencies]
libc = "0.2"
nix = "0.14"
rand = "0.7"
tokio = "0.2.0-alpha.5"
tokio-net = { version = "0.2.0-alpha.5", features = ["signal"] }
net2 = "0.2"
clap = {version = "2.33", features = ["yaml", "color"]}
log = "0.4"
env_logger = "0.6"
serde = {version = "1.0", features = ["rc"]}
serde_json = "1.0"
serde_derive = "1.0"
rust-ini = "0.13"
hyper = {version = "0.13.0-alpha.2", optional = true, default-features = false, features = ["unstable-stream"]}
parking_lot = {version = "0.9", features = ["serde"]}
http = "0.1"
prettytable-rs = {version = "0.8", default-features = false}
regex = "1"
lazy_static = "1.3"
number_prefix = "0.3"
futures = { package = "futures-preview", version = "=0.3.0-alpha.18", default-features = false, features = ["compat"] }
httparse = "1.3"

[features]
default = ["web_console"]
web_console = ["hyper"]
