[package]
name = "moproxy"
version = "0.1.6"
authors = ["sorz <me@sorz.org>"]

[dependencies]
libc = "0.2"
nix = "0.9"
rand = "0.3"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-uds = "0.1"
net2 = "0.2"
clap = {version = "2.29", features = ["yaml"]}
log = "0.3"
env_logger = "0.4"
serde = {version = "1.0", features = ["rc"]}
serde_json = "1.0"
serde_derive = "1.0"
rust-ini = "0.10"
hyper = "0.11"

[dependencies.systemd]
git = "https://github.com/jmesmon/rust-systemd.git"
