name: build-package

on:
  push:
    tags:
      - v*

jobs:
  build-unix:
    name: Build and upload binaries and pre-build packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-deb
          use-tool-cache: true
      - uses: actions-rs/cargo@v1
        with:
          command: deb
          args: -- --all-features
      - run: xz -kfS "_${GITHUB_REF#*/v}_amd64.bin.xz" target/release/moproxy 
      - uses: ncipollo/release-action@v1
        with:
          artifacts: target/debian/*.deb,target/release/*.bin.xz
          token: ${{ secrets.GITHUB_TOKEN }}
