name: build-package

on:
  push:
    tags:
      - v*

jobs:
  build-linux:
    name: Build for
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-deb
          use-tool-cache: true
      - uses: actions-rs/cargo@v1
        with:
          command: deb
          args: -- --all-features
      - run: xz -kfS "_${GITHUB_REF#*/v}_linux_amd64.bin.xz" target/release/moproxy 
      - uses: ncipollo/release-action@v1
        with:
          artifacts: target/debian/*.deb,target/release/*.bin.xz
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - run: xz -kf target/release/moproxy.exe > "moproxy_${GITHUB_REF#*/v}_windows_amd64.exe.xz"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: target/release/*.exe.xz
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
